### ISSUE TITLE
temporary outage for chaotic aur

### ISSUE THREAD

**Issue by ryanmusante** [PedroHLC/chaotic-aur#1]
How do I force pacman to bypass and update even when the custom repository is down? (without commenting out pacman.conf)
```
error: failed retrieving file 'chaotic-aur.db' from lonewolf-builder.duckdns.org : Could not resolve host: lonewolf-builder.duckdns.org
error: failed to update chaotic-aur (invalid url for server)
error: failed to synchronize all databases

```

**Comment by PedroHLC** [comment]
One is now able to find this repo through [ipfs](https://ipfs.io), as well as mirror it and seed:
https://ipfs.io/ipns/QmYeyXJNBGJtAsyb62pVXGyYAGUUUfyHEr9qB8e73FLHSr

I'll soon put my desktop to mirror it, It has 100mb of upload, should hold us fine when official link is down...

I'm also trying to activate [a gateway](cloudflare-ipfs.com) at:
https://lonewolf-ipfs.pedrohlc.com/

**Comment by PedroHLC** [comment]
Thanks to @BangL we now have  a full mirror at:
http://chaotic.bangl.de/chaotic-aur

**Comment by ryanmusante** [comment]
@PedroHLC awesome!
