### ISSUE TITLE
All package fails to build

### ISSUE THREAD

**Issue by Ashraaf** [PedroHLC/chaotic-aur#10]
By the look of online live console, it appear that the mount point under ./root/home/main-builder/* have been missing and caused all package to fail building.

**Comment by Ashraaf** [comment]
All seem fine now somehow.., closing.

**Comment by PedroHLC** [comment]
Sorry, I was away today. I also don't know what happened, graphics and logs didn't show anything unusual and yet IO was unresponsive... I'll keep watching...
