### ISSUE TITLE
404 on repo

### ISSUE THREAD

**Issue by andrevmatos** [PedroHLC/chaotic-aur#11]
Seems like something is wrong, all files, including .db files, seems gone. 
Btw, thank you for this repo, it's so useful! Unicamp fellow here ;)

**Comment by PedroHLC** [comment]
So, I was in Cryptorave, doing some manual builds through ssh through my phone, and I decided to clean some dirty in my workspace and I accidentally issued a `rm -rf` in a container with bindings mounts to the real `/srv`, I already started rebuilding everything, but do expect a few less pkgs (currently broken pkgs and removed from AUR), I hope I get at leasy 700 of them back in the next 2 hours.

**Comment by andrevmatos** [comment]
No problem, just created the issue in the case something happened and you wouldn't be aware of it. Thank you
