### ISSUE TITLE
Consider using llvm-minimal-git for building mesa-git

### ISSUE THREAD

**Issue by Ashraaf** [PedroHLC/chaotic-aur#12]
Newer aur mesa-git now defaulted to stable llvm from Arch's extra repo to ease up dependencies hassle for some people. (https://bbs.archlinux.org/viewtopic.php?pid=1845029#p1845029)

But as stated by Lone_Wolf on mesa-git aur pages "If you build against stable llvm things MAY work, but you're likely to lack some features and face stability issues."

So, I suggest we use llvm-minimal-git for building mesa-git since this repo provide the needed dependencies for user (llvm-libs-minimal-git), which can be installed alongside Arch's stable llvm-libs. The only drawback is the additional llvm-libs-minimal-git and lib32-llvm-libs-minimal-git for 32 bit package.

**Comment by PedroHLC** [comment]
:thinking: it used to be built using `lone_wof-*`, but it seems like behavior changed in AUR, I'll change it and start a recompilation...

**Comment by PedroHLC** [comment]
Done, feel free to reopen in case something goes wrong again...
