### ISSUE TITLE
[linux-clear] adjust '_subarch=' to 26

### ISSUE THREAD

**Issue by mmetak** [PedroHLC/chaotic-aur#13]
Hi, maintainer of linux-clear package in aur here.

As per user request I've set _subarch= to 27 to use native optimizations so you should adjust your package accordingly, set it to 26 to use generic optimizations.

**Comment by PedroHLC** [comment]
That's not very usual, but if they demanded... I removed the package, automated the change and started a new build manually, will be available soon.

**Comment by mmetak** [comment]
I guess the kind of users who use this kernel are gamers and others that want the maximum they can get. IDK.
Hope this change doesn't make it too difficult for you?

**Comment by PedroHLC** [comment]
Nah, just one more if in the makepkg wrapper with a sed, I do things the KISS way. If you're satisfied with the new build, feel free to close the issue.

**Comment by mmetak** [comment]
Should be fine now. Just checked the config file and it says `CONFIG_GENERIC_CPU=y`.
Glad to hear it's not a big problem for you and everyone is satisfied. ;-)

**Comment by mmetak** [comment]
@PedroHLC Hi, sorry to bother you again, but the latest version of gcc optimizations patch added new zen2 option and number for generic changed. It's now `27`.

**Comment by PedroHLC** [comment]
Changed it and is now rebuilding, could it be '99', '0', 'false', or 'none' instead?

**Comment by mmetak** [comment]
I'm afraid not. [That's the way the patch is made.](https://github.com/graysky2/kernel_gcc_patch)

```
# Optionally select a sub architecture by number if building in a clean chroot
# Leaving this entry blank will require user interaction during the build
# which will cause a failure to build if using makechrootpkg. Note that the
# generic (default) option is 27.
```
If you don't want this patch applied you can just set `_enable_gcc_more_v="n"` in `PKGBUILD`.

**Comment by mmetak** [comment]
@PedroHLC Could you replace this line:
```
sed -i'' 's/^_subarch=.*$/_subarch=27/g' PKGBUILD
```
with something like this?
```
sed -i 's/^_subarch=.*/_subarch='"$(grep Generic-x86-64 PKGBUILD | awk -F '.' '{print $1}' | awk '{print $2}')"'/g' PKGBUILD
```

Seems like graysky will add more architectures to the patch and change numbers regularly  and this would solve that.

**Comment by mmetak** [comment]
I check the `.config` file in your repo build and it seems like that sed above is working properly.
`CONFIG_GENERIC_CPU=y`
