### ISSUE TITLE
wine-tkg faudio variant is not needed now

### ISSUE THREAD

**Issue by kprkpr** [PedroHLC/chaotic-aur#20]
Hi
I'm using your repo and I see that you have versiones with "-faudio-"

wine-tkg scripts enable ever faudio as wine 4.3 and wine-staging 4.13+
"\# Faudio - Use the currently installed Faudio packages (both 32 and 64-bit) for xaudio2 - Fixes sound issues in various games. Disables xaudio2 & winepulse staging patchsets
\# Support is enabled by default in Wine 4.3+ as well as Wine-staging 4.13+, independently of this setting
_use_faudio="true" "

You don't need to build this variants ;) 

Thanks for all!

**Comment by PedroHLC** [comment]
Thanks for the intel, I'll remove them but first I'm asking tkg if he can add a tag to automatically move people with `-faudio` pkgs to the default, they're 200 at least...

**Comment by PedroHLC** [comment]
Solved by tkg in 3c11886b2985fa7c5a07b8e35a2aec885617a7ab
I've removed the -faudio pkgs and I'm rebuilding the others, users won't be required to do any action when updating...

**Comment by PedroHLC** [comment]
Tested and confirmed working!
