### ISSUE TITLE
32bit LLVM git breaks linking

### ISSUE THREAD

**Issue by ronoverdrive** [PedroHLC/chaotic-aur#21]
It produces libLLVM-10svn.so & libLLVM-10.0.0svn.so instead of libLLVM-10.so & libLLVM-10.0.0.so in /usr/lib32. This breaks compatibility when compiling MESA-git for example since it cannot find the correct libraries.

**Comment by PedroHLC** [comment]
Please report this error to the corresponding package in [AUR](https://aur.archlinux.org/packages/), we're just building their packages all the maintenance is left for the mantainer who owns the package there.
