### ISSUE TITLE
Anbox should be rebuilded 'couse of libprotobuf update

### ISSUE THREAD

**Issue by kirill9617** [PedroHLC/chaotic-aur#22]
`anbox: error while loading shared libraries: libprotobuf-lite.so.18: cannot open shared object file: No such file or directory`

**Comment by PedroHLC** [comment]
I tried, but it's trying to use an unavailable member of protobuf during compilation, so seems that it's incompatible with current protobuf version

**Comment by PedroHLC** [comment]
More information here:
https://github.com/anbox/anbox/issues/1276

**Comment by PedroHLC** [comment]
I built one now with https://github.com/anbox/anbox/pull/1280/files#diff-af3b638bc2a3e6c650974192a53c7291 applied
