### ISSUE TITLE
Request: lmms-git

### ISSUE THREAD

**Issue by Tremeschin** [PedroHLC/chaotic-aur#24]
https://aur.archlinux.org/packages/lmms-git/

https://github.com/LMMS/lmms

ty; vlws <3

**Comment by PedroHLC** [comment]
Done, please test it...

**Comment by Tremeschin** [comment]
Yes, everything looks fine. Could load VSTs through Wine with vestige and the default LADSPA plugins, compose with the piano roll, playlist, ran through PulseAudio and JackAudio to test sound output and load a full example project.

Just took a while because I was getting a derpy error I was getting yesterday of the program getting stuck on the loading screen with one core at 100% usage. Thought it was a recent commit bug but turned out was a config file here I missed. 

Thank you!!
