### ISSUE TITLE
consider adding citra-canary-git and decaf-emu-git

### ISSUE THREAD

**Issue by dnmodder** [PedroHLC/chaotic-aur#25]
If you can, I have recently adopted the decaf-emu-git package and updated it

**Comment by PedroHLC** [comment]
`citra-canary-git` I've successfully added, but `decaf-emu-git` is missing python (needed as building from a clean chroot)

**Comment by dnmodder** [comment]
Ok, I updated it, I added python as makedepends and also glslang since it was necessary too, can you try again?

**Comment by PedroHLC** [comment]
Nice, it works. Good work!
Thanks for adopting it, fixing it and requesting to be added.
