### ISSUE TITLE
llvm-* and lib32-llvm* package not building.

### ISSUE THREAD

**Issue by Ashraaf** [PedroHLC/chaotic-aur#26]
Its have been a few days since the last llvm-* and lib32-llvm* package in this repo updated 
while there is many new commit in llvm-project.

I cant find them in the list of [failing pkg logs](https://lonewolf.pedrohlc.com/chaotic-aur/makepkglogs/).

**Comment by PedroHLC** [comment]
Good noticed, I'll take a look

**Comment by Ashraaf** [comment]
Both package successfully updated just now, thank you for looking into it.

**Comment by PedroHLC** [comment]
I'll reopen cause it didn't build today again

**Comment by Ashraaf** [comment]
Meanwhile, can i suggest that you change the ordering of building llvm package?, 
i mean llvm-* and then its lib32-llvm-*, currently its llvm-git ~ llvm-minimal-git ~ lib32-llvm-git and lib32-minimal-git.

Due to the fast paced llvm development and the long time it takes to compile llvm-*, by the time the lib32-llvm-* start compiling, their version will be too much ahead of their 64bit version.

Anyway, its just my suggestion, im happy with the current setup and no need to change if its too much hassle.

**Comment by PedroHLC** [comment]
Ok, I've put the lib32 to build after its counterpart now, but it would be better to start them simultaneously. When I have time I'll make this change and fix the automatic builds, today I had to start them manually again...

**Comment by Ashraaf** [comment]
Thank you for considering it, i really appreciate it. Yeah, simultaneously start them would be better, in the past i have faced a boot problem due to rebooting after updating llvm-libs package while its lib32-* still not updated yet.

So the problem lies with autobuild setup?, i thought it was compilation error, I never successfully build the 64bit package after waiting for hours, ccc1plus something always get killed even when i reduce -j to half my cpu number..

**Comment by PedroHLC** [comment]
The problem actually is with the service unit's script I've written to start the build. Here is the log of the last build (I use this directory for builds I start manually):
https://lonewolf.pedrohlc.com/chaotic-aur/makepkglogs/_lab/all_llvm.log

**Comment by Ashraaf** [comment]
Does the new llvm-* updated just now you manually started or builded automatically as it should?

**Comment by PedroHLC** [comment]
Yesterday wasn't but today was.
Thanks for reporting it.
