### ISSUE TITLE
switch package format to .tar.zst

### ISSUE THREAD

**Issue by soredake** [PedroHLC/chaotic-aur#28]

**Comment by PedroHLC** [comment]
Please, add size and performance comparisons  so I'll be sure about doing this change

**Comment by PedroHLC** [comment]
I've made a pool on telegram channel for voting this out!

**Comment by PedroHLC** [comment]
We've got 71% interested in this switch, so it'll happen.
But by now I either have to wait for [this commit](https://github.com/cassava/repoctl/commit/6b15ca44804a531c90d9fb9c37564b89a8f52000) to enter `master` or `repoctl-git` to adopt `devel` branch.

**Comment by PedroHLC** [comment]
I've added `repoctl-devel-git` to AUR, made the necessaries changes to my scripts, and it's working.

**Comment by PedroHLC** [comment]
Solved as seen on 6d70368
