### ISSUE TITLE
Drop D9VK-* packages as it already merged in DXVK projects.

### ISSUE THREAD

**Issue by Ashraaf** [PedroHLC/chaotic-aur#29]
Commit [54ed8f0](https://github.com/doitsujin/dxvk/commit/54ed8f0bb0f0859e05b7b406b7e95fa71900ba40) has successfully merged in the ['Implement Direct3D9 Frontend'](https://github.com/doitsujin/dxvk/pull/1275) pull requests into DXVK projects.

Users of dxvk no longer need to install d9vk separately now its combined in 1 package.

**Comment by PedroHLC** [comment]
Wow, congratulations to Josh.
I think AUR packagers should merge their packages in AUR too.

**Comment by ssorgatem** [comment]
I just updated dxvk-bin

**Comment by PedroHLC** [comment]
Ok, I've added `dxvk-bin`, `d{9,x}vk-mingw-git` should still be adjusted in AUR.

**Comment by ssorgatem** [comment]
The dxvk-{mingw,winelib}-git packages are updated.

I am not the maintainer of the d9vk or other dxvk packages.

**Comment by PedroHLC** [comment]
Hey @Ashraaf  and @ssorgatem , I could drop `d9vk-*-git`, but for that it would be good if `dxvk-*-git`  used a `replace` option so people who has it will receive dxvk as an update. What do you guys think?

**Comment by ssorgatem** [comment]
That's a very good idea.
I'll add it to the AUR packages right now,

**Comment by Ashraaf** [comment]
Yeah, I think its good.

**Comment by PedroHLC** [comment]
That's it, thanks
