### ISSUE TITLE
ManoRequest

### ISSUE THREAD

**Issue by ryukinix** [PedroHLC/chaotic-aur#3]
- [ ] awesome-freedesktop-git
- [ ] awesome-git
- [ ] exercism-cli
- [ ] godot
- [ ] appeditor-git
- [ ] tmate
- [ ] ttygif
- [ ] ttyrec
- [x] microchip-mplabx-bin
- [x] microchip-mplabxc8-bin
- [x] roswell

**Comment by ryukinix** [comment]
https://aur.archlinux.org/packages/wps-office-stable/ this shit as well

**Comment by PedroHLC** [comment]
Done, it already had `godot`

**Comment by ryukinix** [comment]
COOL! THANKS!
