### ISSUE TITLE
Add wine-staging-tkg with vkchildwindow patch enabled

### ISSUE THREAD

**Issue by dnmodder** [PedroHLC/chaotic-aur#30]
This is necesary for Cemu 1.16.0 Vulkan backend

**Comment by PedroHLC** [comment]
I'll ask TkG what he things about enabling it for all my builds, just to make sure there wouldn't be undesired consequences.
If there is, I could create a build just for Cemu.

**Comment by PedroHLC** [comment]
Ok, he said it shouldn't have problems. It's building right now...

**Comment by PedroHLC** [comment]
All builds since 2019-12-21 are/will include this patch.
