### ISSUE TITLE
Request adding spirv-tools-git package

### ISSUE THREAD

**Issue by Ashraaf** [PedroHLC/chaotic-aur#31]
Stable vkd3d provided by arch official repo doesn't depend on spirv-tools but vkd3d-git provided in this repo, [aur](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=vkd3d-git#n10) and [Tk-Glitch](https://github.com/Tk-Glitch/PKGBUILDS/blob/master/vkd3d-git/PKGBUILD#L45), all depends on it.

Since the arch's spirv-tools is quite outdated (19 July 2019 last updated), I request adding spirv-tools-git package, preferably from [Tk-Glitch](https://github.com/Tk-Glitch/PKGBUILDS/tree/master/spirv-tools-git) since its also build lib32 package.

Thank you.

**Comment by PedroHLC** [comment]
:grinning: sorry, I thought we already had this one, adding it now.
I should update the index to list which packages are from TkG instead of AUR...
Thanks for the contribution! 😊
