### ISSUE TITLE
request: openmw-git and vita3k-git

### ISSUE THREAD

**Issue by soredake** [PedroHLC/chaotic-aur#34]

**Comment by PedroHLC** [comment]
openmw went great
vita3k-git seems to miss an include header file from boost, probably a missing dep of when building from a clean chroot, and this needs to be fixed in AUR.
Here's the building log: https://lonewolf.pedrohlc.com/chaotic-aur/makepkglogs/_lab/vita3k-git.log

**Comment by PedroHLC** [comment]
Finally was able to build vita3k-git.
