### ISSUE TITLE
consider adding below packages

### ISSUE THREAD

**Issue by librewish** [PedroHLC/chaotic-aur#4]
gamehub 
itch
steamlink twitch gui
fancontrol-kcm
gwe - green with envy
scrcpy
ttf-ms-fonts
exe-thumbnailer
q4wine

anbox all packages
mycroft ai and plasma plugin

**Comment by PedroHLC** [comment]
```
exe-thumbnailer
fancontrol-kcm
gamehub
gwe
itch
q4wine
scrcpy
streamlink-twitch-gui
ttf-ms-fonts
```

added those. Could you list the ones you want from anbox, mycroft and plasma?
Also, I'm not sure I could have added ttf-ms-fonts, hope they'll notify me in case I couldn't...

**Comment by librewish** [comment]
anbox-git
anbox-modules-dkms-git
anbox-bridge
anbox-image
mycroft-core 
plasma5-applets-mycroft-git


also if you could add these packages
from https://cubocore.gitlab.io/
https://gitlab.com/cubocore/wiki/tree/master/ArchPackages

**Comment by PedroHLC** [comment]
Ok, done, but:
* not every cubocore package are building, `libcplayer coregarage coretime` are broken, you can see their logs here: https://lonewolf.pedrohlc.com/chaotic-aur/makepkglogs/_daily/cubocore
* `anbox-git` is also broken

**Comment by librewish** [comment]
https://forum.manjaro.org/t/anbox-git-compile-error-a-failure-occurred-in-build/78947
this person compiled it at the end

about the cubocore packages i will notify the dev 
and thanks for adding these

**Comment by librewish** [comment]
the pkgbuild for cubocore apps are fixed 
they will now build.
so please add them.

**Comment by PedroHLC** [comment]
:smile:  it was already added in the automated process, so they added themselves...

**Comment by librewish** [comment]
so does that mean when anbox-git is able to be build it will be added automatically to the repo?

**Comment by PedroHLC** [comment]
could you request the author to merge or replicate those fixes? It's not cool to use forks for this...

For AUR packages I need to build it successfully once for it to keep automatically build it forever...

**Comment by librewish** [comment]
okay i asked the author to merge those fixes.it will be fixed

**Comment by ryanmusante** [comment]
Can these be added?

```
ananicy-git 
dolphin-emu-git 
emulationstation 
grml-rescueboot 
gzdoom-git 
modprobed-db 
onedrive-abraunegg-git 
openvpn-git 
pinta-git 
qt5-webengine-widevine 1
qtwebflix-git 
qzdl 
simplicity-sddm-theme-git 
transmission-gtk-git 
ungoogled-chromium-bin 
zdoom 
```

**Comment by PedroHLC** [comment]
@librewish thank you very much! 😁
@ryanmusante, added them all!
