### ISSUE TITLE
Request: Linux-lqx

### ISSUE THREAD

**Issue by Elanzer47** [PedroHLC/chaotic-aur#40]
it's possible to add
https://aur.archlinux.org/packages/linux-lqx/
to the repo??

I cound't find any repo with it.

Thanks.

**Comment by PedroHLC** [comment]
I'll add.
Just a question, shouldn't `linux-zen` be identical to this one?

**Comment by Elanzer47** [comment]
> I'll add.
> Just a question, shouldn't `linux-zen` be identical to this one?

I really dont know. There's no documentation regarding `linux-zen`, and people say it's the same, but the same guy responsible for zen-patchset is the packager of `linux-lqx`, which is weird, so IMHO liquorix includes zen-patch plus some extra features.

Same guy (Steven Barrett):
https://github.com/zen-kernel
https://aur.archlinux.org/cgit/aur.git/log/?h=linux-lqx

**Comment by PedroHLC** [comment]
Same guy? That's awesome.
It's in the repo right now. Please, test it and if it works you can close the issue.

Thanks for the request and the research!
