### ISSUE TITLE
Add brave or brave-bin from aur.

### ISSUE THREAD

**Issue by b4skyx** [PedroHLC/chaotic-aur#41]
Currently the brave browser, both in binary or source compiled package is missing in the repo. I think brave is a widely used browser, thus request you to add it in the chaotic aur repo.

**Comment by Yardanico** [comment]
I'd have to disagree that it's a "widely used browser", but nothing against including it in the repo

**Comment by librewish** [comment]
i think it was in repo 🤔 
perhaps it got removed when repo cleaning process anyway will add it

**Comment by PedroHLC** [comment]
Added them both :smile:
