### ISSUE TITLE
Request: chromium-ozone

### ISSUE THREAD

**Issue by SmitTheTux** [PedroHLC/chaotic-aur#42]
It would be nice to have chromium-ozone in repo
https://aur.archlinux.org/packages/chromium-ozone/

**Comment by PedroHLC** [comment]
Added. Please test it :smile:
Feel free to close the issue if it works as expected.

**Comment by SmitTheTux** [comment]
I tested it.
It seems its running. I can see chromium processes in KDE system monitor but nothing shows up. Its not usable (at least in kwin_wayland)

**Comment by SmitTheTux** [comment]
its working with version 81 update on kde plasma. I also needed to remove this flag` --enable-native-gpu-memory-buffers` from .config/chromium-flags.conf
