### ISSUE TITLE
 package kwin-lowlatency requires clean rebuild

### ISSUE THREAD

**Issue by timescam** [PedroHLC/chaotic-aur#45]
the one in repo cannot identify the latest version of libkdecorations2private.so (kdecoration)
a clean build with the PKGBUILD on aur fixed it on my end

**Comment by PedroHLC** [comment]
I rebuilt it, please test it (you're probably gonna need to refresh the package in your pacman's cache).
If it works, feel free to close this issue!

**Comment by timescam** [comment]
fixed
