### ISSUE TITLE
Linux-tkg packages don't get updated

### ISSUE THREAD

**Issue by barfin** [PedroHLC/chaotic-aur#47]

**Comment by PedroHLC** [comment]
Everything is okay with daily kernels build, I started it now and it's building, I think there was some broken commit that was fixed btw 4days ago and today.
Newer packages should appear in a few minutes (PDS first, then BMQ, then MuQSS), and tomorrow by the end of the day it shall be finished.
When the package you like gets built, please test it, and if it works feel free to close this issue.
