### ISSUE TITLE
ungoogled-chromium is outdated

### ISSUE THREAD

**Issue by Danilopereira82** [PedroHLC/chaotic-aur#48]
demora muito?

**Comment by PedroHLC** [comment]
[PT-BR]
O pacote do AUR está atualmente quebrado:
https://github.com/ungoogled-software/ungoogled-chromium-archlinux/issues/57
O log da compilação que o chaotic-aur tenta toda hora pode ser visto em:
https://lonewolf.pedrohlc.com/chaotic-aur/makepkglogs/ungoogled-chromium.log

Como eu cuido de muitos pacotes aqui eu costumo não intervir em problemas no PKGBUILD e ao invés cobro os mantenedores no AUR para consertarem o problema para todos.

**Comment by Danilopereira82** [comment]
ta bom
😘
