### ISSUE TITLE
vkbasalt is outdated

### ISSUE THREAD

**Issue by axredneck** [PedroHLC/chaotic-aur#49]
vkbasalt in chaotic-aur is 0.2.2-1 while in AUR it's 0.3.0-4

**Comment by PedroHLC** [comment]
Nice noticed, manually updated and left a comment for the maintainer to permanently fix it.
I also added `reshade-shaders-git`.
Please test it, and if it works, close this issue!
:smile:

**Comment by axredneck** [comment]
Thank you, vkBasalt works. Though i didn't try Reshade shaders because ones shipped with vkBasalt are enough for me.
