### ISSUE TITLE
Consider creating patreon

### ISSUE THREAD

**Issue by ryanmusante** [PedroHLC/chaotic-aur#5]
Can you make a patreon for people to donate to you to help your work and costs of maintenance?

**Comment by PedroHLC** [comment]
😫 actually, I believe I can't as this is sort of an experiment which UFSCAR (especially @thotyo
pous) kindly allowed me to do. My job there is to test and optimize their cloud infrastructure, to be more precise to develop a billing solution. So it wouldn't be ethically correct for me to receive for resources which were lent for me for other projects benefits.
It would be interesting though if one could mirror it in a personal vps (just static files, no building).

**Comment by ryanmusante** [comment]
Ahh, yes hopefully someone can step up and provide a mirror.
