### ISSUE TITLE
pacman doesn't download updates from chaotic-aur

### ISSUE THREAD

**Issue by kabbalah10** [PedroHLC/chaotic-aur#50]
Greetings, I followed all the instructions to add the repositories to /etc/pacman.conf, but I noticed that the gnome-extension-dash-to-dock update of February 13th in the repos didn't apply it, although, while doing pacmans -Syyu updates to chaotic as a whole, it seems like it doesn't read the repositories, I don't know if I am clear, but I would like to know how to solve this problem.

Sincronizando las bases de datos de los paquetes...
 testing                                                                                 41,7 KiB   151 KiB/s 00:00 [######################################################################] 100%
 core                                                                                   135,9 KiB   118 KiB/s 00:01 [######################################################################] 100%
 extra                                                                                 1639,6 KiB   128 KiB/s 00:13 [######################################################################] 100%
 community-testing                                                                       33,4 KiB   229 KiB/s 00:00 [######################################################################] 100%
 community                                                                                4,8 MiB   202 KiB/s 00:24 [######################################################################] 100%
 archlinuxcn                                                                           1310,9 KiB   135 KiB/s 00:10 [######################################################################] 100%
 andontie-aur                                                                           111,9 KiB   231 KiB/s 00:00 [######################################################################] 100%
 andontie-aur.sig                                                                       310,0   B  0,00   B/s 00:00 [######################################################################] 100%
 chaotic-aur                                                                            901,2 KiB   141 KiB/s 00:06 [######################################################################] 100%
 Reborn-OS                                                                              204,0 KiB   206 KiB/s 00:01 [######################################################################] 100%

**Comment by PedroHLC** [comment]
Hi, it can be one of two things:
1) as you have more than one repo other, could be that one of those (anyone that is before "chaotic-aur" in `/etc/pacman.conf`) has the same package and it's from it that you're installing.
2) If you put one of the mirrors before the official link, they do have a sync latency of a few minutes, so updates come later on them.

My recommendation would be:
1) Pull chaotic-aur up in /etc/pacman.conf (bellow community and archlinuxcn)
2) Use powerpill, keeping the chaotic-aur's servers sequence as instructed on the home page. (I also recommend using this to update: `sudo pacman -Sy && sudo powerpill -Su && yay -Su`)
3) If you want to pick the server you can prefix it as a path, like this: `pacman -S chaotic-aur/dxvk-mingw-git`

**Comment by kabbalah10** [comment]
Thanks for the answer, I put chaotic after community, installed powerpill,
followed your instructions and all is going well, again thanks.

Julio Cesar
