### ISSUE TITLE
request: add pacui and pacui-git

### ISSUE THREAD

**Issue by timescam** [PedroHLC/chaotic-aur#51]
[pacui](https://github.com/excalibur1234/pacui) is a bash script that provides text interface for pacman and aur helpers. Currently it is not on the aur ([reasons](https://forum.manjaro.org/t/pacui-removed-from-aur/54716/51)), and only available in manjaro's repo

PKGBUILD for latest release: [https://raw.githubusercontent.com/excalibur1234/pacui/master/PKGBUILD](https://raw.githubusercontent.com/excalibur1234/pacui/master/PKGBUILD)

PKGBUILD for latest commit: [https://raw.githubusercontent.com/excalibur1234/pacui/master/PKGBUILD-git](https://raw.githubusercontent.com/excalibur1234/pacui/master/PKGBUILD-git)

**Comment by PedroHLC** [comment]
The arch's reasons for it not to be in AUR are quite real. It's not secure and totally not failure-proof.
But you were advised and it's your choice to use it or not.
As they're not in AUR, I'll just build them nightly.

I've added them. Test, and if it works, close this issue.

**Comment by timescam** [comment]
tested, thanks
