### ISSUE TITLE
mangohud-git need a clean build

### ISSUE THREAD

**Issue by dnmodder** [PedroHLC/chaotic-aur#52]
It fails with this error:

`ERROR: /home/main-builder/pkgsrc/mangohud is not a clone of https://github.com/flightlessmango/MangoHud`

I think you need to delete the source folder, because I changed the source to git+https://github.com/flightlessmango/MangoHud#branch=develop

**Comment by PedroHLC** [comment]
:thinking:  there is something wrong, mangohud was supposed to be using the author's PKGBUILDS from:
https://github.com/flightlessmango/PKGBUILDS/blob/master/mangohud/PKGBUILD

**Comment by PedroHLC** [comment]
Sorry, a long time ago @flightlessmango requested his package to be used instead of AUR.
More recently he renamed it to `-git`. And now packages are building in the repo, that's what generated this error.

**Comment by dnmodder** [comment]
Ok I understand

**Comment by flightlessmango** [comment]
@dnmodder At the time there wasn't a AUR package for mangohud so I made on, that's pretty much the extent of my involvement. I would be more than happy if we could use your AUR PKGBUILD instead, gets it off my plate

**Comment by dnmodder** [comment]
@flightlessmango It would be fine, I will be updating the package as necessary and you would have something less to take care of.

**Comment by PedroHLC** [comment]
Ok, moved to AUR packages. That's better for me too, cause it updates hourly instead of daily.
Also added a list of non-aur packages in `index.html`

**Comment by PedroHLC** [comment]
Closing, and mentioning as a reminder to work on #9
