### ISSUE TITLE
"mangohud" and "lib32-mangohud" are stuck in version 2.0-4

### ISSUE THREAD

**Issue by barfin** [PedroHLC/chaotic-aur#57]
the latest version of mangohud in aur is 3.1-1

**Comment by PedroHLC** [comment]
Hi, thanks, it seems I had accidentally reverted an old ignore list.

Glad you helped me, new version should come in with the next hourly releases.

**Comment by PedroHLC** [comment]
Ok, it seems they all updated, thanks for the notification!
Sorry for any trouble.
