### ISSUE TITLE
packages request

### ISSUE THREAD

**Issue by soredake** [PedroHLC/chaotic-aur#59]
1. lib32-gst-plugins-ugly (+deps)
2. lib32-gst-plugins-bad (+deps)

**Comment by PedroHLC** [comment]
These two took me a lot of work, so many recursive deps (more than 60), and I had to do it manually cause repoctl isn't resolving them for me :joy: 

But it's done! Test it and if it works, please close the issue. Feel free to leave any feedback.

**Comment by soredake** [comment]
Sorry for trouble, and thanks!
