### ISSUE TITLE
nvidia-tkg needs patch to build DKMS module on kernel 5.6.

### ISSUE THREAD

**Issue by BrianAllred** [PedroHLC/chaotic-aur#62]
Without TKG's patch, nvidia-tkg doesn't build the DKMS module on kernel 5.6. Building manually from TKG's repo works because it detects your kernel version and applies the patch automatically.

The patch looks to be backwards compatible with previous kernels as the required code is surrounded with `ifdef`s, and it compiles the DKMS module on my 5.5 kernel just fine.

**Comment by PedroHLC** [comment]
By now I removed them, following TkG's advice...
Thanks again!

Cheers,
PedroHLC.

**Comment by ryanmusante** [comment]
They're not in the repo just temporarily?
```
~ >>> yay -Qm                                                                                                   
lib32-nvidia-utils-tkg 440.64-102
lib32-opencl-nvidia-tkg 440.64-102
nvidia-dkms-tkg 440.64-102
nvidia-egl-wayland-tkg 440.64-102
nvidia-utils-tkg 440.64-102
opencl-nvidia-tkg 440.64-102
```

**Comment by PedroHLC** [comment]
We are studying (@Tk-Glitch and me), searching for a scenario, where the DKMS won't break so much.

By now I'm considering pre-compiled binaries for the linux-tkg-* packages I maintain, and a DKMS built for linux-mainline.

**Comment by PedroHLC** [comment]
**[UPDATE]**
* So, by now, I've created a `chaotic-nvidia-all-tkg`, this is Nvidia modules for all the kernels in chaotic-aur (and in the next build for core too).
* This doesn't resolve unsyncs (gcc and kernels updates).
* I'm considering how I'll handle unsyncs; probably I'll have to adopt pkgver and pkgrel different from TkG's. Maybe instead I'll find a way to constraint the users to update both kernel and drivers.
* There is also a dkms module. Use that on your risk!
* The difference in pkgbase's name will allow users that prefer to use TkG to not update automatically when chaotic dumps a new borked version. (like @kassindornelles)
* These pkgnames are here to stay. I won't rename them anymore!

**Comment by ryanmusante** [comment]
>     * This doesn't resolve unsyncs (gcc and kernels updates).
Do you mean this when during updates?
```
( 6/12) Updating linux initcpios...
==> Building image from preset: /etc/mkinitcpio.d/linux-tkg-bmq-haswell.preset: 'default'
  -> -k /boot/vmlinuz-linux-tkg-bmq-haswell -c /etc/mkinitcpio.conf -g /boot/initramfs-linux-tkg-bmq-haswell.img
==> Starting build: 5.6.3-8-tkg-bmq
  -> Running build hook: [base]
  -> Running build hook: [udev]
  -> Running build hook: [autodetect]
  -> Running build hook: [modconf]
  -> Running build hook: [block]
  -> Running build hook: [keyboard]
  -> Running build hook: [keymap]
  -> Running build hook: [filesystems]
  -> Running build hook: [fsck]
==> ERROR: module not found: `nvidia'
==> ERROR: module not found: `nvidia_modeset'
==> ERROR: module not found: `nvidia_uvm'
==> ERROR: module not found: `nvidia_drm'
==> Generating module dependencies
==> Creating uncompressed initcpio image: /boot/initramfs-linux-tkg-bmq-haswell.img
==> WARNING: errors were encountered during the build. The image may not be complete.
==> Building image from preset: /etc/mkinitcpio.d/linux-tkg-bmq-haswell.preset: 'fallback'
  -> -k /boot/vmlinuz-linux-tkg-bmq-haswell -c /etc/mkinitcpio.conf -g /boot/initramfs-linux-tkg-bmq-haswell-fallback.img -S autodetect
==> Starting build: 5.6.3-8-tkg-bmq
  -> Running build hook: [base]
  -> Running build hook: [udev]
  -> Running build hook: [modconf]
  -> Running build hook: [block]
  -> Running build hook: [keyboard]
  -> Running build hook: [keymap]
  -> Running build hook: [filesystems]
  -> Running build hook: [fsck]
==> ERROR: module not found: `nvidia'
==> ERROR: module not found: `nvidia_modeset'
==> ERROR: module not found: `nvidia_uvm'
==> ERROR: module not found: `nvidia_drm'
```

**Comment by PedroHLC** [comment]
Yep, I'm thinking on how to handle this as I wiped all packages yesterday

**Comment by PedroHLC** [comment]
I've been using `chaotic-nvidia-dev-dkms-tkg` for some time now, it seems there is no better solution than DKMS. As this is a fork, I have the ability to change pkgrel at my will. But you're gonna have to notify me everytime compilations fails. Closing this by now.

**Comment by ryanmusante** [comment]
I'm running it now, all good.
