### ISSUE TITLE
Seems like wf-shell is not in sync with AUR

### ISSUE THREAD

**Issue by scruffidog** [PedroHLC/chaotic-aur#63]
AUR is reporting wf-shell as version 0.4.0 while the Chaotic repository is still on 0.3-2. Any chance this can get updated ? Otherwise everything looks great!

**Comment by PedroHLC** [comment]
The repo tries to build it every hour, but it's been unsuccessful, you can see the failing logs:
https://lonewolf.pedrohlc.com/chaotic-aur/makepkglogs/wf-shell.log 

The repo builds in a clean container, so, like in this case, the AUR maintainer needs to add every dependence required for building, cause the server can't guess them.

Please, help me reporting the missing dep to  https://aur.archlinux.org/packages/wf-shell

**Comment by scruffidog** [comment]
Thanks! Will do.

**Comment by PedroHLC** [comment]
I'll leave this issue open, as I'm also tracking this :smile:

**Comment by PedroHLC** [comment]
Ok, solved!
