### ISSUE TITLE
lib32-ffmpeg needs to be recompiled against new lib32-x265 and lib32-dav1d

### ISSUE THREAD

**Issue by jporterf** [PedroHLC/chaotic-aur#65]
Unable to compile wine-tkg (I need certain settings) because it fails on FAudio, which if failing because libavcodec can't find libdav1d.so.3 or libx265.so.179 which do not exist on the chaotic-aur versions of these files.

**Comment by PedroHLC** [comment]
Ok, it's built. Note: as this change doesn't bump pkgrel or epoch (those should be done by the AUR maintainer) the update will not happen automatically. You'll have to ask pacman to sync it again and probably delete the older package from cache.
