### ISSUE TITLE
mesa-git depends on llvm-libs=9.0.1

### ISSUE THREAD

**Issue by asiantuntija** [PedroHLC/chaotic-aur#68]
Is there something blocking usage of newer versions of LLVM? It used to work with llvm-git a while ago.

**Comment by PedroHLC** [comment]
> It used to work with llvm-git a
Yep, you're right, my mistake.

Rebuilding it...

**Comment by PedroHLC** [comment]
Please test it. And if it works, feel free to close this issue.

You might prefer to use `mesa-tkg-git`, it constrains that both lib32- and non-multilib variants are built from the same source/version.

**Comment by asiantuntija** [comment]
The reason I was requesting this was that Arch bumped LLVM to version 10 and mesa-git was locked to version 9, I should had been more clear about this. The updated version seems to be running just fine.

If you want, requiring just llvm-libs instead of llvm-libs-minimal-git would save you some bandwidth. Thanks for the help and offering this repository.

**Comment by PedroHLC** [comment]
`llvm-libs-minimal-git` can be co-installed with arch's `llvm-libs`, this way you can have mesa-git without breaking rustc for example.
I'll be closing this issue, feel free to reopen if it breaks again.
