### ISSUE TITLE
Log of most popular apps

### ISSUE THREAD

**Issue by ryanmusante** [PedroHLC/chaotic-aur#69]
Do you collect statistics on most downloaded applications from the repo? I was hoping there was a way to grab that list if it existed.

**Comment by PedroHLC** [comment]
There is only a "last month" top 25 available here:
https://lonewolf.pedrohlc.com/chaotic-aur/analytics.html
(It includes statistics from the main repo and BangL's mirror, does not include from Kitsuna's mirror)

**Comment by ryanmusante** [comment]
Thanks, that is good.
