### ISSUE TITLE
Package request TKG

### ISSUE THREAD

**Issue by ryanmusante** [PedroHLC/chaotic-aur#7]
Request tkg builds to be added for nvidia (long-lived, currently 418.56-38), proton, and winetricks. 
```
lib32-nvidia-utils-tkg 
lib32-opencl-nvidia-tkg 
nvidia-dkms-tkg 
nvidia-egl-wayland-tkg 
nvidia-utils-tkg 
opencl-nvidia-tkg 
proton-tkg
winetricks-tkg-git
```

**Comment by PedroHLC** [comment]
Sorry for not replying, I indeed forgot it. TkG packages are a little trick cause they requires more handwork. Most of his packages aren't suitable for generic building. But I do have interesting in adding proton-tkg, after that is actually working I'll try the others.

**Comment by ryanmusante** [comment]
The main reason is so that I can automatically grab and update nvidia-tkg from the chaotic-aur repo instead of having to manually extract and install from the TKG repos each time. That way to avoid this error on tkg kernel installs.
```
==> ERROR: module not found: `nvidia'
==> ERROR: module not found: `nvidia_modeset'
==> ERROR: module not found: `nvidia_uvm'
==> ERROR: module not found: `nvidia_drm'
==> Generating module dependencies
==> Creating uncompressed initcpio image: /boot/initramfs-linux51-tkg-bmq.img
==> WARNING: errors were encountered during the build. The image may not be complete.
```

**Comment by PedroHLC** [comment]
Ok, I'll take the day to add `nvidia-all`, `winetricks-tkg-git` and `proton-tkg`
