### ISSUE TITLE
add "obfs4proxy" or/and "obfs4-git"

### ISSUE THREAD

**Issue by barfin** [PedroHLC/chaotic-aur#70]

**Comment by PedroHLC** [comment]
I'm adding both, please test `obfs4proxy`.
If it's working, feel free to close this issue.
Otherwise please comment your issue in here.

**Comment by barfin** [comment]
> I'm adding both, please test `obfs4proxy`.
> If it's working, feel free to close this issue.
> Otherwise please comment your issue in here.

thanks it works
