### ISSUE TITLE
DIGIKAM

### ISSUE THREAD

**Issue by johnbrz** [PedroHLC/chaotic-aur#71]
could you add this package?
https://aur.archlinux.org/packages/digikam-git/

**Comment by PedroHLC** [comment]
Done.
Test it, see if it's working. And if it is, feel free to close this issue!

**Comment by johnbrz** [comment]
thanks!

How are git packages handled in your repository? Is there a predefined interval between builds?

**Comment by PedroHLC** [comment]
They build hourly, with some exceptions that are daily, and some broken ones that are waiting to be fixed.

**Comment by johnbrz** [comment]
ok
