### ISSUE TITLE
/usr/share/libalpm/scripts/cleanup already in file system

### ISSUE THREAD

**Issue by simona70** [PedroHLC/chaotic-aur#72]
Now linux-tkg-pds and linux-tkg-muqss cannot be installed in the same time.

**Comment by PedroHLC** [comment]
@TkGlitch is already aware of this problem, and it's working on a fix

**Comment by simona70** [comment]
thx

**Comment by PedroHLC** [comment]
Please let me know if the problem still persists

**Comment by simona70** [comment]
Now ok. Installed pmq muqss pds with noi problem.
Only linux-tkg-pds-zen conflict with tkg-pds

---------------------------------------------------------------------------------------------------------------------------------------
Simona


Il giorno mer 6 mag 2020 alle ore 01:05 Pedro <notifications@github.com> ha
scritto:
