### ISSUE TITLE
can't upgrade "nohang-git"

### ISSUE THREAD

**Issue by barfin** [PedroHLC/chaotic-aur#73]
![Screenshot from 2020-05-02 18-54-16](https://user-images.githubusercontent.com/37030489/80867663-9e83fb00-8caa-11ea-946d-6b7b7b11931a.png)

**Comment by PedroHLC** [comment]
Please submit this issue in https://aur.archlinux.org/packages/nohang-git/

**Comment by barfin** [comment]
> Please submit this issue in https://aur.archlinux.org/packages/nohang-git/

you're right I'm sorry
