### ISSUE TITLE
Latest Plasmafox fails to launch

### ISSUE THREAD

**Issue by wazlecracker** [PedroHLC/chaotic-aur#74]
The newest version of plasmafox fails to launch. This is the error when trying:
```
XPCOMGlueLoad error for file /usr/lib/plasmafox/libxul.so:
libicui18n.so.67: cannot open shared object file: No such file or directory
Couldn't load XPCOM.
```
On Manjaro KDE, plasma 5.18.4.1-1
Kernel 5.6.8-1
Plasmafox v75.0-3

**Comment by librewish** [comment]
we have uploaded the rebuilt version.
no pkegrel changes so
to use it first clear the cache the download it.

**Comment by PedroHLC** [comment]
I see this was solved in https://github.com/torvic9/plasmafox/issues/17
So closing it!
Thanks @librewish
