### ISSUE TITLE
Request: Linux-xanmod

### ISSUE THREAD

**Issue by raziel100** [PedroHLC/chaotic-aur#75]
I wonder if this kernel could d be add to the repository:

https://aur.archlinux.org/packages/linux-xanmod/

**Comment by PedroHLC** [comment]
I can add, but first, what is the particular reason for preferring this kernel and not the others in this repo?

**Comment by raziel100** [comment]
it was a kernel I has used on ubuntu and it performed better than zen or liquorix for me

**Comment by PedroHLC** [comment]
I forgot to update that I've added it last night.
Please test it. And if it works, feel free to close this issue.

**Comment by raziel100** [comment]
I has works great. Thanks.

**Comment by ItsiAdam** [comment]
@PedroHLC What build options are you using?
Personally I would rather this, which is also what the maintainer of the linux-xanmod pkgbuilds uses.
use_tracers=n use_numa=n use_pds=y use_ns=y

**Comment by PedroHLC** [comment]
@ItsiAdam please open a new issue, I want more feedback about it.
