### ISSUE TITLE
ffmpeg-full is broken

### ISSUE THREAD

**Issue by raziel100** [PedroHLC/chaotic-aur#79]
after install the ffmpeg-full the error "error while loading shared libraries: libkvazaar.so.4: cannot open shared object file: No such file or directory" appear in almost every application, i normaly don't use this package, i just have tested it.

**Comment by PedroHLC** [comment]
I rebuilt and bumped pkgrel, let me know if it worked, I'll need to file a new issue with a proper long-term solution...

**Comment by raziel100** [comment]
it has worked just fine now
