### ISSUE TITLE
Wine-tkg-staging builds are not staging

### ISSUE THREAD

**Issue by Gigabyte29** [PedroHLC/chaotic-aur#8]
I tried with wine-tkg-staging-esync-faudio-git and wine-tkg-staging-esync-git and both weren't staging

**Comment by PedroHLC** [comment]
Sorry, I don't understand, do you mean it's without staging patchs?

**Comment by Gigabyte29** [comment]
Yes sorry for my english 😅

**Comment by PedroHLC** [comment]
Ok, found that nothing was building since yesterday, I just put the server to recompile TkG's pkgs

**Comment by Gigabyte29** [comment]
It's still without staging patches

**Comment by Ashraaf** [comment]
Tested with today's wine-tkg-staging-esync-faudio-git-4.6.r1.gcbb09031-153, still no staging tab in winecfg and its dll also missing in override menu, e.g., nvapi64.dll

Also, dxvk winelib are outdated, probally build issue with meson 0.50?

**Comment by PedroHLC** [comment]
Not sure why dxvk-win updated and dxvk-wine didn't, will averiguate it tomorrow. I changed how it's cleaning wine-tkg src now, please check again when this builds finishes, sorry for all this trouble.

**Comment by Ashraaf** [comment]
Still no staging tab in winecfg with newer wine-tkg-staging-esync-faudio-git-4.6.r3.g36e84f29-153

**Comment by Ashraaf** [comment]
Tried with Arch's official wine-staging-4.6-1 and the staging tab is there.

**Comment by ryanmusante** [comment]
Strange, I don't see the tab either.

**Comment by PedroHLC** [comment]
I think dxvk-wine-git will build every hour again now, thanks for noticing.
I'll send TkG a message, maybe he'll know what's going on here. I believe it has to do with me using a global source cache in makepkg.conf

**Comment by ryanmusante** [comment]
I appreciate that you take time to help!
