### ISSUE TITLE
ungoogled-chromium-git

### ISSUE THREAD

**Issue by johnbrz** [PedroHLC/chaotic-aur#82]
hi, i'm here again xD

could you add this package?
https://aur.archlinux.org/packages/ungoogled-chromium-git/

The "normal" `ungoogled-chromium` package breaks in almost every update and the maintainer doesn't seem to be willing to fix it.

**Comment by johnbrz** [comment]
and this one: https://aur.archlinux.org/packages/jellyfin-git/

**Comment by PedroHLC** [comment]
Sorry for the late response, building both now.

Do note that those will be in daily slots (so not building hourly).

**Comment by johnbrz** [comment]
the digikam I had previously requested is compiled every hour, could you exchange it for ungoogled-chromium-git? Since the browser has more need for faster updates (because of security updates) it makes more sense that it has more priority.

**Comment by PedroHLC** [comment]
The problem is that a build this size will slow down all the others. One chrome-based browser build takes the same amount of `time x resources` as 50x digikam builds.

Don't worry, a -git building daily is what Mozilla calls "Nightly".

**Comment by johnbrz** [comment]
I understand. Thank you!
