### ISSUE TITLE
lavalaunch 1.7.0

### ISSUE THREAD

**Issue by scruffidog** [PedroHLC/chaotic-aur#84]
Would you consider pulling lavalaunch into you pre-built repository ?

https://aur.archlinux.org/packages/lavalauncher/

The pkgbuild is written by the developer himself.... :)

**Comment by PedroHLC** [comment]
Mantainer/Developer fixed it, and it's now in, with the -git package too.

**Comment by scruffidog** [comment]
You are awesome. Thanks for being so responsive!
