### ISSUE TITLE
Request: wine-x64

### ISSUE THREAD

**Issue by erkexzcx** [PedroHLC/chaotic-aur#87]
Title. This package is needed for `winbox64` (another AUR package), but since there is no binary wine 64bit package available, would you don't mind adding it to your repo?

Thanks!

**Comment by PedroHLC** [comment]
Both packages are bizarre, `multilib/wine*` is built with both x32 and x64 support and provide a `wine64` binary. It's not like there is a version of windows64 that doesn't supports windows32.
But okay, I'll add them both...

**Comment by PedroHLC** [comment]
Ok, added, please test them both.
If they work, feel free to close this issue.
